<?php

declare(strict_types=1);

namespace Shredio\Core\Formatter;

final class CurrencyDatabase
{
	/** @var array<string, array{string, bool}> */
	final protected const array Currencies = [
		'GBX' => ['GBX', false],
		'GBp' => ['GBX', false],
		'USD' => ['$', true],
		'CAD' => ['CA$', false],
		'EUR' => ['€', true],
		'AED' => ['AED', false],
		'AFN' => ['Af', false],
		'ALL' => ['ALL', false],
		'AMD' => ['AMD', false],
		'ARS' => ['AR$', false],
		'AUD' => ['AU$', false],
		'AZN' => ['man.', false],
		'BAM' => ['KM', false],
		'BDT' => ['Tk', false],
		'BGN' => ['BGN', false],
		'BHD' => ['BD', false],
		'BIF' => ['FBu', false],
		'BND' => ['BN$', false],
		'BOB' => ['Bs', false],
		'BRL' => ['R$', false],
		'BWP' => ['BWP', false],
		'BYN' => ['Br', false],
		'BZD' => ['BZ$', false],
		'CDF' => ['CDF', false],
		'CHF' => ['CHF', false],
		'CLP' => ['CL$', false],
		'CNY' => ['CN¥', true],
		'COP' => ['CO$', false],
		'CRC' => ['₡', false],
		'CVE' => ['CV$', false],
		'CZK' => ['Kč', false],
		'DJF' => ['Fdj', false],
		'DKK' => ['Dkr', false],
		'DOP' => ['RD$', false],
		'DZD' => ['DA', false],
		'EEK' => ['Ekr', false],
		'EGP' => ['EGP', false],
		'ERN' => ['Nfk', false],
		'ETB' => ['Br', false],
		'GBP' => ['£', true],
		'GEL' => ['GEL', false],
		'GHS' => ['GH₵', false],
		'GNF' => ['FG', false],
		'GTQ' => ['GTQ', false],
		'HKD' => ['HK$', false],
		'HNL' => ['HNL', false],
		'HRK' => ['kn', false],
		'HUF' => ['Ft', false],
		'IDR' => ['Rp', false],
		'ILS' => ['₪', false],
		'INR' => ['Rs', false],
		'IQD' => ['IQD', false],
		'IRR' => ['IRR', false],
		'ISK' => ['Ikr', false],
		'JMD' => ['J$', false],
		'JOD' => ['JD', false],
		'JPY' => ['¥', true],
		'KES' => ['Ksh', false],
		'KHR' => ['KHR', false],
		'KMF' => ['CF', false],
		'KRW' => ['₩', true],
		'KWD' => ['KD', false],
		'KZT' => ['KZT', false],
		'LBP' => ['L.L.', false],
		'LKR' => ['SLRs', false],
		'LTL' => ['Lt', false],
		'LVL' => ['Ls', false],
		'LYD' => ['LD', false],
		'MAD' => ['MAD', false],
		'MDL' => ['MDL', false],
		'MGA' => ['MGA', false],
		'MKD' => ['MKD', false],
		'MMK' => ['MMK', false],
		'MOP' => ['MOP$', false],
		'MUR' => ['MURs', false],
		'MXN' => ['MX$', false],
		'MYR' => ['RM', false],
		'MZN' => ['MTn', false],
		'NAD' => ['N$', false],
		'NGN' => ['₦', false],
		'NIO' => ['C$', false],
		'NOK' => ['Nkr', false],
		'NPR' => ['NPRs', false],
		'NZD' => ['NZ$', false],
		'OMR' => ['OMR', false],
		'PAB' => ['B/.', false],
		'PEN' => ['S/.', false],
		'PHP' => ['₱', true],
		'PKR' => ['PKRs', false],
		'PLN' => ['zł', false],
		'PYG' => ['₲', false],
		'QAR' => ['QR', false],
		'RON' => ['RON', false],
		'RSD' => ['din.', false],
		'RUB' => ['RUB', false],
		'RWF' => ['RWF', false],
		'SAR' => ['SR', false],
		'SDG' => ['SDG', false],
		'SEK' => ['Skr', false],
		'SGD' => ['S$', false],
		'SOS' => ['Ssh', false],
		'SYP' => ['SY£', false],
		'THB' => ['฿', false],
		'TND' => ['DT', false],
		'TOP' => ['T$', false],
		'TRY' => ['TL', false],
		'TTD' => ['TT$', false],
		'TWD' => ['NT$', false],
		'TZS' => ['TSh', false],
		'UAH' => ['₴', false],
		'UGX' => ['USh', false],
		'UYU' => ['$U', false],
		'UZS' => ['UZS', false],
		'VEF' => ['Bs.F.', false],
		'VND' => ['₫', false],
		'XAF' => ['FCFA', false],
		'XOF' => ['CFA', false],
		'YER' => ['YR', false],
		'ZAR' => ['R', false],
		'ZMK' => ['ZK', false],
		'ZWL' => ['ZWL$', false],
	];

	/**
	 * @return array{symbol: string, isBefore: bool}|null
	 */
	public static function getCurrencyConfiguration(string $currency): ?array
	{
		if (!($config = self::Currencies[$currency] ?? null)) {
			return null;
		}

		return [
			'symbol' => $config[0],
			'isBefore' => $config[1],
		];
	}
}
